config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root 'static_pages#landing_page'
  # get 'static_pages/index'
  get 'pricing', to: 'static_pages#pricing'
  get 'about', to: 'static_pages#about'
  get 'privacy', to: 'static_pages#privacy'
  get 'terms', to: 'static_pages#terms'

  get 'dashboard', to: 'home#dashboard'

  resources :users, only: [:index, :show] do
    member do
      patch :resend_invitation
    end
  end

  resources :tenants do
    get :my, on: :collection
    member do
      patch :switch
    end
  end

  resources :members, execpt: [:create, :new] do
    get :invite, on: :collection
  end

  resources :contacts

  get 'tenants/:tenant_id/leads/new', to: 'leads#new', as: :new_lead
  get 'tenants/:tenant_id/leads/:id', to: 'leads#show', as: :tenant_lead
  match 'tenants/:tenant_id/leads', to: 'leads#create', via:[ :post ], as: :create_lead
end

app/models/tenant.rb
class Tenant < ApplicationRecord
  extend FriendlyId
  RESERVED_NAMES = %w(blog app pricing terms help support tenant tenants user users sex organization)
  RESERVED_PLANS = %w(solo team)
  PLANS = [:solo, :team]

  has_one_attached :logo
  validates :logo, content_type: [:png, :jpg, :jpeg],
    size: { less_than: 100.kilobytes, message: 'must be smaller than 100 KB' }

  validates :name, presence: true, uniqueness: true
  validates :name, length: { in: 2..20 }
  validates :name, exclusion: { in: RESERVED_NAMES, message: "%{value} is reserved" }
  validates :plan, presence: true
  validates :plan, inclusion: { in: RESERVED_PLANS, message: "%{value} is not available" }

  has_many :members, dependent: :destroy
  has_many :users, through: :members
  has_many :contacts, dependent: :destroy

  friendly_id :name, use: :slugged

  def should_generate_new_friendly_id?
    name_changed?
  end

  def to_s
    name
  end

  def can_invite_members?
    self.plan == "team" 
  end
end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  before_action :set_tenant, only: %i[ show edit update destroy switch ]
  before_action :require_admin, only: %i[ edit update destroy ]
  before_action :require_member, only: %i[ show ]

  set_current_tenant_through_filter

  # GET /tenants or /tenants.json
  def index
    @tenants = Tenant.includes(:members, :users, members: [:user])
  end

  def switch
    if current_user.tenants.include?(@tenant)
      current_user.update_attribute(:tenant_id, @tenant.id)
      redirect_to my_tenants_path, notice: "Switched to tenant: #{current_user.tenant.name}"
    else
      redirect_to my_tenants_path, alert: "You are not authorized to access tenant: #{@tenant.name}"
    end
  end

  def my
    @tenants = current_user.tenants
    render 'index'
  end

  # GET /tenants/1 or /tenants/1.json
  def show
    set_current_tenant(@tenant)
  end

  # GET /tenants/new
  def new
    @tenant = Tenant.new
  end

  # GET /tenants/1/edit
  def edit
  end

  # POST /tenants or /tenants.json
  def create
    @tenant = Tenant.new(tenant_params)

    respond_to do |format|
      if @tenant.save
        @member = Member.create!(tenant: @tenant, user: current_user, admin: true)
        current_user.update_attribute(:tenant_id, @tenant.id)
        format.html { redirect_to @tenant, notice: "Tenant was successfully created." }
        format.json { render :show, status: :created, location: @tenant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tenant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tenants/1 or /tenants/1.json
  def update
    respond_to do |format|
      if @tenant.update(tenant_params)
        format.html { redirect_to @tenant, notice: "Tenant was successfully updated." }
        format.json { render :show, status: :ok, location: @tenant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tenant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tenants/1 or /tenants/1.json
  def destroy
    @tenant.destroy

    respond_to do |format|
      format.html { redirect_to my_tenants_path, status: :see_other, notice: "Tenant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tenant
      @tenant = Tenant.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tenant_params
      params.require(:tenant).permit(:name, :plan, :logo)
    end

    def require_admin
      return if current_user.tenants.include?(@tenant) && Member.find_by(user: current_user, tenant: @tenant).admin?
    
      redirect_to tenants_path, alert: "You are not authorized"
    end

    def require_member
      return if current_user.tenants.include?(@tenant)

      redirect_to tenants_path, alert: "You are not authorized"
    end
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/views/tenants/_form.html.erb
<%= simple_form_for(@tenant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :plan, collection: Tenant::PLANS, include_blank: false, as: :radio_buttons, item_wrapper_class: 'radio-item' %>
    <% if @tenant.logo.attached? %>
      <%= image_tag @tenant.logo, size: "50x50", class: "rounded" %>
      <%= @tenant.logo.filename %>
      <%= number_to_human_size(@tenant.logo.byte_size) %>
    <% end %>

    <%= f.input :logo %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tenants/edit.html.erb
<% provide(:breadcrumb) do %>
  <%= mount_breadcrumb([
    ['Início', root_path],
    ['Tenants', tenants_path],
    ['Edit']
  ]) %>
<% end %>

<div class="card shadow">
  <div class="card-header">
    <h4>Editing Tenant</h4>
  </div>
  <div class="card-body">
    <%= render 'form', tenant: @tenant %>
  </div>
  <div class="card-footer">
    <%= link_to 'Show', @tenant %> |
    <%= link_to 'Back', tenants_path %>
  </div>
</div>

app/views/tenants/index.html.erb
<% provide(:breadcrumb) do %>
  <%= mount_breadcrumb([
    ['Início', root_path],
    ['Tenants']
  ]) %>
<% end %>

<h3>
  <div class="text-center">
    <%= controller_name.humanize + ":" %>
    <%= action_name.humanize %>

    <div class="badge badge-purple">
      <%= @tenants.count %>
    </div>
  </div>
</h3>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover shadow">
    <thead>
      <tr>
        <th>id</th>
        <th>logo</th>
        <th>name</th>
        <th>plan</th>
        <th colspan="4">users</th>
      </tr>
    </thead>
    <tbody>
      <% @tenants.each do |tenant| %>
        <tr>
          <td>
            <% if current_user.tenants.include?(tenant) %>
              <%= link_to tenant.id, tenant %>
            <% else %>
              <%= tenant.id %>
            <% end %>
          </td>
          <td><%= image_tag tenant.logo, size: "25x25", class: "rounded" if tenant.logo.attached? %></td>
          <td><%= tenant.name %></td>
          <td><%= tenant.plan %></td>
          <td><%= tenant.users.compact.join(', ') %></td>
          <td>
            <% if current_user.tenants.include?(tenant) %>
              <% if current_user.tenant == tenant %>
              <span class="badge text-bg-success">
                current_tenant
              </span>
              <% else %>
                <%= link_to 'Switch tenant', switch_tenant_path(tenant), method: :patch %>
              <% end %>
            <% end %>
          </td>
          <% if current_user.tenants.include?(tenant) && Member.find_by(user: current_user, tenant: tenant).admin? %>
            <td><%= link_to 'Edit', edit_tenant_path(tenant) %></td>
            <td><%= link_to 'Destroy', tenant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% else %>
            <td colspan="2"></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tenants/new.html.erb
<% provide(:breadcrumb) do %>
  <%= mount_breadcrumb([
    ['Início', root_path],
    ['Tenants', tenants_path],
    ['New']
  ]) %>
<% end %>

<div class="card shadow">
  <div class="card-header">
    <h4>New Tenant</h4>
  </div>
  <div class="card-body">
    <%= render 'form', tenant: @tenant %>
  </div>
  <div class="card-footer">
    <%= link_to 'Back', tenants_path %>
  </div>
</div>

app/views/tenants/show.html.erb
<% provide(:breadcrumb) do %>
  <%= mount_breadcrumb([
    ['Início', root_path],
    [@tenant.name]
  ]) %>
<% end %>

<div class="card shadow">
  <div class="card-header">
    <h4>
      <strong>Name:</strong>
      <%= @tenant.name %>
    </h4>
  </div>
  <div class="card-body">
    <strong>Members:</strong>
    <%= @tenant.users.compact.join(', ') %> <br>

    <strong>Members count:</strong>
    <%= @tenant.members.count %> <br>

    <strong>Plan:</strong>
    <%= @tenant.plan %> <br>
  
    <strong>Logo:</strong>
    <%= image_tag @tenant.logo, size: "50x50", class: "rounded" if @tenant.logo.attached? %>
  </div>
  <div class="card-footer">
    <% if current_user.tenants.include?(@tenant) && Member.find_by(user: current_user, tenant: @tenant).admin? %>
      <%= link_to 'Edit', edit_tenant_path(@tenant) %>
    <% end %>

    <%= link_to 'Back', tenants_path %>
  </div>
</div>