config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root 'static_pages#landing_page'
  # get 'static_pages/index'
  get 'pricing', to: 'static_pages#pricing'
  get 'about', to: 'static_pages#about'
  get 'privacy', to: 'static_pages#privacy'
  get 'terms', to: 'static_pages#terms'

  get 'dashboard', to: 'home#dashboard'

  resources :users, only: [:index, :show] do
    member do
      patch :resend_invitation
    end
  end

  resources :tenants do
    get :my, on: :collection
    member do
      patch :switch
    end
  end

  resources :members, execpt: [:create, :new] do
    get :invite, on: :collection
  end

  resources :contacts

  get 'tenants/:tenant_id/leads/new', to: 'leads#new', as: :new_lead
  get 'tenants/:tenant_id/leads/:id', to: 'leads#show', as: :tenant_lead
  match 'tenants/:tenant_id/leads', to: 'leads#create', via:[ :post ], as: :create_lead
end

app/models/contact.rb
class Contact < ApplicationRecord
  # belongs_to :tenant
  acts_as_tenant(:tenant)

  validates :first_name, :last_name, :phone_number, :email, presence: true
  validates_uniqueness_of :phone_number, scope: :tenant_id
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  include SetTenant
  include RequireTenant
  include SetCurrentMember

  before_action :set_contact, only: %i[ show edit update destroy ]
  before_action :require_admin_or_editor, only: %i[ edit update destroy ]

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_path, status: :see_other, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :phone_number, :email)
    end

    def require_admin_or_editor
      return if @current_member&.admin? || @current_member&.editor?
    
      redirect_to contacts_path, alert: "You are not authorized"
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= simple_form_for(@contact) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :phone_number %>
    <%= f.input :email %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<% provide(:breadcrumb) do %>
  <%= mount_breadcrumb([
    ['Início', root_path],
    ['Contacts', contacts_path],
    ['Edit']
  ]) %>
<% end %>

<div class="card shadow">
  <div class="card-header">
    <h4>Editing Contact</h4>
  </div>
  <div class="card-body">
    <%= render 'form', contact: @contact %>
  </div>
  <div class="card-footer">
    <%= link_to 'Show', @contact %> |
    <%= link_to 'Back', contacts_path %>
  </div>
</div>

app/views/contacts/index.html.erb
<% provide(:breadcrumb) do %>
  <%= mount_breadcrumb([
    ['Início', root_path],
    ['Contacts']
  ]) %>
<% end %>

<h3>
  <div class="text-center">
    <%= controller_name.humanize + ":" %>
    <%= action_name.humanize %>

    <div class="badge badge-purple">
      <%= @contacts.count %>
    </div>
  </div>
</h3>

<%= link_to new_contact_path, class: 'btn btn-primary' do %>
  <i class="fas fa-plus"></i>
  New Contact
<% end %>

<%= link_to new_lead_path(current_tenant), class: 'btn btn-primary' do %>
  <i class="fas fa-plus"></i>
  New Lead
<% end %>
<p>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover shadow">
    <thead>
      <tr>
        <th>id</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Phone number</th>
        <th>Email</th>
        <th>Tenant</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @contacts.each do |contact| %>
        <tr>
          <td><%= link_to contact.id, contact %></td>
          <td><%= contact.first_name %></td>
          <td><%= contact.last_name %></td>
          <td><%= contact.phone_number %></td>
          <td><%= contact.email %></td>
          <td><%= contact.tenant.name %></td>
          <% if @current_member.admin? || @current_member.editor? %>
            <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
            <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/contacts/new.html.erb
<% provide(:breadcrumb) do %>
  <%= mount_breadcrumb([
    ['Início', root_path],
    ['Contacts', contacts_path],
    ['New']
  ]) %>
<% end %>

<div class="card shadow">
  <div class="card-header">
    <h4>New Contact</h4>
  </div>
  <div class="card-body">
    <%= render 'form', contact: @contact %>
  </div>
  <div class="card-footer">
    <%= link_to 'Back', contacts_path %>
  </div>
</div>

app/views/contacts/show.html.erb
<% provide(:breadcrumb) do %>
  <%= mount_breadcrumb([
    ['Início', root_path],
    ['Contacts', contacts_path],
    [@contact.first_name]
  ]) %>
<% end %>

<div class="container">
  <div class="card shadow">
    <div class="card-header">
      <h4>
        <strong>Contact id:</strong>
        <%= @contact.id %>
      </h4>
    </div>
    <div class="card-body">
    <p>
      <strong>First name:</strong>
      <%= @contact.first_name %>
    </p>

    <p>
      <strong>Last name:</strong>
      <%= @contact.last_name %>
    </p>

    <p>
      <strong>Phone number:</strong>
      <%= @contact.phone_number %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @contact.email %>
    </p>

    <p>
      <strong>Tenant:</strong>
      <%= @contact.tenant.name %>
    </p>

    </div>
    <div class="card-footer">
      <% if @current_member %>
        <% if @current_member.admin? || @current_member.editor? %>
          <%= link_to 'Edit', edit_contact_path(@contact) %>
        <% end %>
      <% end %>
      <%= link_to 'Back', contacts_path %>
    </div>
  </div>
</div>