config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root 'static_pages#landing_page'
  # get 'static_pages/index'
  get 'pricing', to: 'static_pages#pricing'
  get 'about', to: 'static_pages#about'
  get 'privacy', to: 'static_pages#privacy'
  get 'terms', to: 'static_pages#terms'

  get 'dashboard', to: 'home#dashboard'

  resources :users, only: [:index, :show] do
    member do
      patch :resend_invitation
    end
  end

  resources :tenants do
    get :my, on: :collection
    member do
      patch :switch
    end
  end

  resources :members, execpt: [:create, :new] do
    get :invite, on: :collection
  end

  resources :contacts

  get 'tenants/:tenant_id/leads/new', to: 'leads#new', as: :new_lead
  get 'tenants/:tenant_id/leads/:id', to: 'leads#show', as: :tenant_lead
  match 'tenants/:tenant_id/leads', to: 'leads#create', via:[ :post ], as: :create_lead
end

app/views/layouts/_breadcrumb.html.erb
<div class="container-fluid py-2">
  <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <% if content_for?(:breadcrumb) %>
      <ol class="breadcrumb">
        <%= yield :breadcrumb %>
      </ol>
    <% end %>
  </nav>
</div>

app/views/layouts/_footer.html.erb
<div class="bg-light py-3">
  <div class="container d-flex flex-column flex-md-row justify-content-center align-items-center text-center gap-2">
    <div>© My SaaS <%= Time.now.year %></div>
    <%= link_to 'About', about_path, class: 'text-decoration-none' %>
    <%= link_to 'Pricing', pricing_path, class: 'text-decoration-none' %>
    <%= link_to 'Terms', terms_path, class: 'text-decoration-none' %>
    <%= link_to 'Privacy', privacy_path, class: 'text-decoration-none' %>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to root_path, class: 'navbar-brand' do %>
      <%= image_tag 'mysaas.png', size: "30x30", class: "rounded" %>
      My Saas
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% if current_user %>
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <%= link_to root_path, class: "nav-link #{'active' if current_page?(root_path) }" do %>
              <i class="fas fa-home"></i>
              Home
            <% end %>
          </li>

          <li class="nav-item">
            <%= link_to users_path, class: "nav-link #{'active' if current_page?(users_path) }" do %>
              <i class="fas fa-users"></i>
              Users
              <span class="badge badge-purple">
                <%= User.count %>
              </span>
            <% end %>
          </li>

          <li class="nav-item">
            <%= link_to tenants_path, class: "nav-link #{'active' if current_page?(tenants_path) }" do %>
              <i class="fas fa-hotel"></i>
              Tenants
              <span class="badge badge-purple">
                <%= Tenant.count %>
              </span>
            <% end %>
          </li>
        </ul>

        <ul class="navbar-nav mr-right">
          <% if current_user.tenants.include?(current_user.tenant) %>
            <%= link_to tenant_path(current_user.tenant), class: "nav-link #{'active' if current_page?(tenant_path(current_user.tenant)) }" do %>
              <% if current_user.tenant.logo.attached? %>
                <%= image_tag current_user.tenant.logo, size: "30x30", class: "rounded" %>
              <% else %>
                <i class="fas fa-briefcase"></i>
              <% end %>
              <%= current_user.tenant.name %>
            <% end %>
          <% end %>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="fas fa-hotel"></i>
              <% if current_user.tenants.include?(current_user.tenant) %>
                Tenants
              <% else %>
                Tenants
              <% end %>
            </a>

            <ul class="dropdown-menu dropdown-menu-end">
              <%= link_to my_tenants_path, class: "dropdown-item #{'active' if current_page?(my_tenants_path) }"  do %>
                <i class="fas fa-hotel"></i>
                My Tenants
              <% end %>

              <li><hr class="dropdown-divider"></li>

              <%= link_to new_tenant_path, class: "dropdown-item #{'active' if current_page?(new_tenant_path) }" do %>
                <i class="fas fa-briefcase"></i>
                New Tenant
              <% end %>
            </ul>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <b><%= current_user.email %></b>
            </a>

            <ul class="dropdown-menu dropdown-menu-end">
              <%= link_to edit_user_registration_path, class: "dropdown-item #{'active' if current_page?(edit_user_registration_path) }" do %>
                <i class="fas fa-user-cog"></i>
                Account settings
              <% end %>

              <li><hr class="dropdown-divider"></li>

              <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
                <i class="fas fa-sign-out-alt"></i>
                Sign out
              <% end %>
            </ul>
          </li>
        </ul>
      <% else %>
        <ul class="navbar-nav me-auto"></ul>
        <ul class="navbar-nav mr-right">
          <li><%= link_to "Register", new_user_registration_path, class: "nav-link #{'active' if current_page?(new_user_registration_path) }" %></li>
          <li><%= link_to "Login", new_user_session_path, class: "nav-link #{'active' if current_page?(new_user_session_path) }" %></li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<div class="sticky-top">
  <ul class="nav flex-column bg-dark shadow rounded">
    <li class="nav-item">
      <%= link_to tenant_path(current_tenant), class: "nav-link #{'bg-light shadow rounded' if current_page?(tenant_path(current_tenant)) }" do %>
        <i class="fas fa-briefcase"></i>
        <%= current_tenant %>
        <% if ActsAsTenant.current_tenant %>
          <span class="badge badge-purple">
            <%= current_tenant.plan %>
          </span>
        <% end %>
      <% end %>
    </li>

    <li class="nav-item">
      <%= link_to dashboard_path, class: "nav-link #{'bg-light shadow rounded' if current_page?(dashboard_path) }" do %>
        <i class="fas fa-tachometer-alt"></i>
        Dashboard
      <% end %>
    </li>

    <li class="nav-item">
      <%= link_to members_path, class: "nav-link #{'bg-light shadow rounded' if request.path.starts_with?(members_path) }" do %>
        <i class="fas fa-users"></i>
        Members
        <% if ActsAsTenant.current_tenant %>
          <span class="badge badge-purple">
            <%= Member.count %>
          </span>
        <% end %>
      <% end %>
    </li>

    <li class="nav-item">
      <%= link_to contacts_path, class: "nav-link #{'bg-light shadow rounded' if request.path.starts_with?(contacts_path) }" do %>
        <i class="fas fa-address-book"></i>
        Contacts
        <% if ActsAsTenant.current_tenant %>
          <span class="badge badge-purple">
            <%= Member.count %>
          </span>
        <% end %>
      <% end %>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag 'mysaas.png', class: "rounded" %>
    <title>My Saas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column min-vh-100">
    <%= render 'layouts/header' %>
    <%= flash_messages %>
    <%= render 'layouts/breadcrumb' %>

    <main class="flex-grow-1">
      <div class="container-fluid">
        <% if ActsAsTenant.current_tenant && current_user.tenants.include?(current_user.tenant) %>
          <div class="row">
            <div class="col-lg-2">
              <%= render 'layouts/sidebar' %>
            </div>
            <div class="col-lg-10">
              <%= yield %>
            </div>
          </div>
        <% else %>
          <%= yield %>
        <% end %>
      </div>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/leads_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= "#{current_tenant.name} #{current_tenant.id}" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column min-vh-100">
    <%= flash_messages %>

    <main class="flex-grow-1">
      <div class="container-fluid py-4">
        <%= yield %>
      </div>
    </main>
  </body>
</html>