config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root 'static_pages#landing_page'
  # get 'static_pages/index'
  get 'pricing', to: 'static_pages#pricing'
  get 'about', to: 'static_pages#about'
  get 'privacy', to: 'static_pages#privacy'
  get 'terms', to: 'static_pages#terms'

  get 'dashboard', to: 'home#dashboard'

  resources :users, only: [:index, :show] do
    member do
      patch :resend_invitation
    end
  end

  resources :tenants do
    get :my, on: :collection
    member do
      patch :switch
    end
  end

  resources :members, execpt: [:create, :new] do
    get :invite, on: :collection
  end

  resources :contacts

  get 'tenants/:tenant_id/leads/new', to: 'leads#new', as: :new_lead
  get 'tenants/:tenant_id/leads/:id', to: 'leads#show', as: :tenant_lead
  match 'tenants/:tenant_id/leads', to: 'leads#create', via:[ :post ], as: :create_lead
end

app/models/member.rb
class Member < ApplicationRecord
  extend FriendlyId

  belongs_to :user, counter_cache: true

  validates :tenant_id, presence: true
  validates_uniqueness_of :user_id, scope: :tenant_id
  validate :must_have_a_role, on: :update
  validate :must_have_an_admin

  acts_as_tenant(:tenant)

  def to_s
    user.email.to_s + tenant.name.to_s
  end

  friendly_id :to_s, use: :slugged

  ROLES = [:admin, :editor, :viewer]

  store_accessor :roles, *ROLES

  ROLES.each do |role|
    scope role, -> { where("roles @> ?", {role => true}.to_json) }
    define_method(:"#{role}=") { |value| super ActiveRecord::Type::Boolean.new.cast(value) }
    define_method(:"#{role}?") { send(role) }
  end

  def active_roles
    ROLES.select { |role| send(:"#{role}?") }.compact
  end

  private

  def must_have_a_role
    if self.roles.values.none?
      errors.add(:base, "A member must have at least one role")
    end
  end

  def must_have_an_admin
    if (self.tenant.members.pluck(:roles).count { |h| h[:'admim'] == true } == 1) && (roles_changed? && admim == false)
      errors.add(:base, "The tenant has to have at least one admim")
    end
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  include SetTenant
  include RequireTenant
  include SetCurrentMember

  before_action :set_member, only: %i[ show edit update destroy ]
  before_action :require_admin, only: %i[ invite edit update destroy ]

  # GET /members or /members.json
  def index
    @members = Member.includes(:user, :tenant).all
  end

  def invite
    email = params[:email]
    user_from_email = User.where(email: email).first

    if current_tenant.can_invite_members?
      if email.present?
        if user_from_email.present?
          if Member.where(user: user_from_email).any?
            redirect_to members_path, alert: "The organization #{current_tenant.name} already has a user with the email #{email}"
          else
            new_member = Member.create!(user: user_from_email, viewer: true)
            MemberMailer.invited(new_member).deliver_now
            redirect_to members_path, notice: "#{email} was invited to join the organization #{current_tenant.name}"
          end
        elsif user_from_email.nil?
          new_user = User.invite!({ email: email }, current_user)
          if new_user.persisted?
            Member.create!(user: new_user, viewer: true)
            redirect_to members_path, notice: "#{email} was invited to join the organization #{current_tenant.name}"
          else
            redirect_to members_path, alert: "Something went wrong. Plase tray again"
          end
        end
      else
        redirect_to members_path, alert: "No email provided!"
      end
    else
      redirect_to members_path, alert: "SOLO plan cannot invite members. Please upgrade your plan!"
    end
  end

  # GET /members/1 or /members/1.json
  def show
  end

  # GET /members/1/edit
  def edit
  end

  # PATCH/PUT /members/1 or /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: "Member was successfully updated." }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1 or /members/1.json
  def destroy
    @member.destroy

    respond_to do |format|
      format.html { redirect_to members_path, status: :see_other, notice: "Member was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def member_params
      params.require(:member).permit(*Member::ROLES)
    end

    def require_admin
      return if @current_member&.admin?

      redirect_to members_path, alert: "You are not authorized"
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= simple_form_for(@member) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-group">
    <% Member::ROLES.each do |role| %>
      <label>
        <%= f.check_box role %>
        <%= role.to_s.humanize %>
      </label>

      <br>
    <% end %>
  </div>


  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<% provide(:breadcrumb) do %>
  <%= mount_breadcrumb([
    ['Início', root_path],
    ['Members', members_path],
    ['Edit'],
  ]) %>
<% end %>

<div class="card shadow">
  <div class="card-header">
    <h4>Editing Member</h4>
    <%= @member.user %>
  </div>
  <div class="card-body">
    <%= render 'form', member: @member %>
  </div>
  <div class="card-footer">
    <%= link_to 'Show', @member %> |
    <%= link_to 'Back', members_path %>
  </div>
</div>

app/views/members/index.html.erb
<% provide(:breadcrumb) do %>
  <%= mount_breadcrumb([
    ['Início', root_path],
    ['Members']
  ]) %>
<% end %>

<h3>
  <div class="text-center">
    <%= controller_name.humanize + ":" %>
    <%= action_name.humanize %>

    <div class="badge badge-purple">
      <%= @members.count %>
    </div>
  </div>
</h3>

<% if @current_member.admin? && current_tenant.can_invite_members? %>
  <%= form_tag invite_members_path, method: :get, class: 'row g-3' do %>
    <div class="col-auto">
      <%= email_field_tag 'email', nil, class: 'form-control', placeholder: 'email' %>
    </div>
    <div class="col-auto">
      <%= submit_tag "Invite a member", class: 'btn btn-primary mb-3' %>
    </div>
  <% end %>
<% end %>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover shadow">
    <thead>
      <tr>
        <th>id</th>
        <th>User</th>
        <th>Tenant id</th>
        <th>Tenant</th>
        <th>invitable</th>
        <th colspan="3">roles</th>
      </tr>
    </thead>
    <tbody>
      <% @members.each do |member| %>
        <tr>
          <td><%= link_to member.id, member %></td>
          <td><%= member.user %></td>
          <td><%= member.tenant.id %></td>
          <td><%= member.tenant %></td>
          <td>
            <% if member.user.created_by_invite? %>
              <span class="badge text-bg-secondary">
                created_by_invite from <%= member.user.invited_by %>
              </span>
              <% if member.user.invitation_accepted_at.present? %>
                <span class="badge text-bg-secondary">
                    invitation accepted
                </span>
              <% else %>
                <%= link_to 'Resend invitation', resend_invitation_user_path(member.user), method: :patch %>
              <% end %>
            <% end %>
          </td>
          <td>
            <%= member.active_roles.join(" ") %>
          </td>

          <% if @current_member.admin? %>
            <td><%= link_to 'Edit', edit_member_path(member) %></td>
            <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% else %>
            <td></td>
            <td></td>
          <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<% provide(:breadcrumb) do %>
  <%= mount_breadcrumb([
    ['Início', root_path],
    ['Members', members_path],
    ['Member']
  ]) %>
<% end %>

<div class="card shadow">
  <div class="card-header">
    <h4>
      <strong>User:</strong>
      <%= @member.user %>
    </h4>
  </div>
  <div class="card-body">
    <strong>Tenant:</strong>
    <%= @member.tenant %>

    <br>

    <strong>Roles:</strong>
    <%= @member.active_roles.join(" ") %>
  </div>
  <div class="card-footer">
    <% if @current_member.admin? %>
      <%= link_to 'Edit', edit_member_path(@member) %>
    <% end %>
    <%= link_to 'Back', members_path %>
  </div>
</div>